### ISSUE TITLE
Example with EventSourcing ?

### ISSUE THREAD

**Issue by macintoshplus** [tyx/ddd-sample-symfony#2]
Is it possible to have an example with EventSourcing?

I know it is difficult to implement the EventSourcing on the Legacy.

What are the changes to the level of the reading model and loading the aggregate?
- The old tables are modified by the event headphones (Event emitted by the aggregate)
- The aggregate is loaded by rerunning past events.

What else ?

**Comment by tyx** [comment]
Hello,

I made another sandbox that works with ES some months ago : 
https://github.com/tyx/cqrs-php-sandbox

But I have not try yet to implement ES on legacy so quite hard to give an example.

Anyway I don't see any blocking point as you mention. 

The legacy table could became your view/snapshot. So you could build your aggregate by running new events from this snapshot.

**Comment by macintoshplus** [comment]
Thank you !

The file organization is free! This gives me ideas to remodel my projects and have a better separation.
